![imagen](./img/ejercicios.png)

## Ejercicio 1
Importa el módulo de `numpy` y obtén su versión.

In [9]:
!pip install numpy
import numpy as np
np.__version__


[notice] A new release of pip is available: 24.0 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


'2.2.4'

## Ejercicio 2
Crea un array de una dimensión que vaya de 0 a 9. Llamalo `my_array`

In [4]:
my_array = np.arange(0, 10)
my_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Ejercicio 3
Crea un array 3x3, que sea todo a True

In [ ]:
array_3_3 = np.array([[1,2,3,4,5], [6,7,8,9,10], [11,12,13,14,15]])


In [8]:
print(array_3_3)
print(array_3_3 <= 16)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[[ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]


## Ejercicio 4
Extrae todos los impares de `my_array`

In [16]:
my_array[(my_array %2 == 1)]


array([1, 3, 5, 7, 9])

## Ejercicio 5
En un nuevo array, sustituye todos los impares de `my_array` por -1

In [12]:
my_array_copy = my_array.copy()
my_array_copy

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
my_array_copy[(my_array %2 == 1)] = -1
my_array_copy

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

## Ejercicio 6
En un nuevo array, sustituye todos los impares de `my_array` por -1. Esta vez usa `where`

In [17]:
my_array_copy2 = my_array.copy()
my_array_copy2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
print(np.where(my_array_copy2 %2 != 0, -1, my_array_copy))

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


## Ejercicio 7
Convierte `my_array` en un nuevo array de dos dimensiones mediante `reshape`.

In [22]:
my_array_2 = my_array.reshape((2,5))
print(my_array_2)

[[0 1 2 3 4]
 [5 6 7 8 9]]


## Ejercicio 8
Concatena los siguientes arrays verticalmente

```Python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

In [24]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

print(a)
print(b)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]


In [26]:


np.vstack([a,b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Ejercicio 9
Concatena los siguientes arrays horizontamente

```Python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

In [27]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
print(a)
print(b)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]


In [ ]:
np.concatenate([a,b], axis = 1) #0 añade en las filas y 1 a las columnas

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [32]:
# de prueba 
np.concatenate([a,b], axis = 0)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Ejercicio 10
Encuentra todos los elementos en común entre ambos arrays. [Para ello usa la función `intersect1d`](https://numpy.org/doc/stable/reference/generated/numpy.intersect1d.html)

```Python
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
```

In [33]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [34]:
np.intersect1d(a, b)

array([2, 4])

## Ejercicio 11
Obtén la documentación acerca de la función `concatenate`

## Ejercicio 12
Crea un array unidimensional que vaya del 0 al 9. Llámalo `my_array`. 
1. Multiplica cada uno de los elementos de `my_array` por 10, en un nuevo array
2. Accede al primer elemento de `my_array`
3. Accede al último elemento de `my_array`
4. Imprime por pantalla los numeros del 1 al 7 de `my_array`

In [35]:
my_array = np.arange(0, 10)

In [37]:
nuevo_array = my_array* 10
nuevo_array

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [39]:
print(my_array[0])

0


In [40]:
print(my_array[-1])

9


In [43]:
print(my_array[1:8])

[1 2 3 4 5 6 7]


## Ejercicio 13
Crea un array manualmente de tres filas por tres columnas. Llámalo `my_matrix`

In [45]:
my_matrix = np.array([[1,2,3], [4,5,6], [7,8,9]])
my_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Ejercicio 14
Obtén la siguiente secuencia:

```Python
[ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49]
```

In [48]:
secuencia = np.arange(1,50,3)

secuencia

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49])

## Ejercicio 15
Crea una secuencia aleatoria. La secuencia se tiene que componer de 4 matrices de 5x3. Serían 3 dimensiones diferentes.

In [60]:
# el primer numero es para definir el inicio de los números que aparecerán en la matriz. El siguient (50) hasta donde puede buscar 
# números randoms.  luego ira size y dentro podremos crear las dimensiones que queramos. en este caso, (5,3) la primera se refiere al
#número de filas que tendrá cáda matriz y la segunda el 3, el número de columnas. El 4 en este caso, representa el número de matrices
#que queremos 
array_15 = (np.random.randint(0, 50, size = (4,5,3)))

array_15

array([[[ 7,  2, 12],
        [27, 26, 21],
        [37, 13, 38],
        [30, 42, 28],
        [42, 10, 47]],

       [[44, 37, 43],
        [ 7,  1, 16],
        [ 1, 41, 37],
        [10, 46,  1],
        [17, 40, 19]],

       [[18,  4, 11],
        [21, 47,  0],
        [18, 10, 13],
        [35,  3, 39],
        [19, 19, 13]],

       [[24, 38, 32],
        [16,  7, 20],
        [11, 28, 21],
        [23, 29,  4],
        [ 4, 18, 23]]], dtype=int32)

## Ejercicio 16
Crea una matriz de 10x1, toda ella compuesta por `False`. Después transformalo en un 2x5

In [ ]:
#np.zeros crea una matriz de tamaño 10x1, donde todos los elementos son 0 (el 0 se interpreta como False
array_false = np.zeros((10, 1), dtype=bool)

array_false

array([[False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False]])

In [66]:
array_false.reshape(2,5)

array([[False, False, False, False, False],
       [False, False, False, False, False]])

## Ejercicio 17
Dado el siguiente array

```Python
x = np.random.randint(10, 20, size = (5,2,6))
```

1. ¿Cuántos elementos tiene el array?
2. ¿Cuántas dimensiones?
3. ¿Cuánta es la longitud cada dimensión?

In [67]:
x = np.random.randint(10, 20, size = (5,2,6))

1. el array tiene 5 matrices de 2 filas y 6 columnas cada una. por tanto 60 elementos.

2. Tiene 3 dimensiones.

3. la longitud de la primera dimensión, tiene 5 elementos

   la longitud de la segunda dimensión, tiene 2 elementos
   
   la longitud de la tercera dimensión, son 6 elementos


In [68]:
x

array([[[18, 15, 14, 15, 12, 18],
        [16, 15, 16, 17, 10, 16]],

       [[11, 11, 13, 18, 17, 14],
        [19, 10, 16, 19, 19, 17]],

       [[14, 16, 16, 13, 10, 14],
        [10, 16, 10, 11, 13, 18]],

       [[15, 15, 13, 16, 19, 16],
        [12, 17, 19, 16, 19, 15]],

       [[11, 11, 15, 17, 10, 10],
        [16, 19, 13, 16, 12, 18]]], dtype=int32)