![imagen](./img/ejercicios.png)

In [1]:
import numpy as np

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [2]:
my_array = np.arange(10)
print(my_array)

[0 1 2 3 4 5 6 7 8 9]


In [3]:
print(my_array[::-2]) #para poder imprimir en orden descendente los números de la lista, 

[9 7 5 3 1]


In [4]:
print(my_array[my_array % 2 == 1][::-1])

[9 7 5 3 1]


## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [5]:
print(my_array)

[0 1 2 3 4 5 6 7 8 9]


In [6]:
print(my_array[-2:-4:-1])

[8 7]


## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [7]:
print(my_array)

[0 1 2 3 4 5 6 7 8 9]


In [8]:
print(my_array[2::-1])

[2 1 0]


In [9]:
print(sorted(my_array[:3],reverse=True))

[np.int64(2), np.int64(1), np.int64(0)]


In [10]:
np.take(my_array, [2,1,0])

array([2, 1, 0])

## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [11]:
my_matrix = np.arange(1,21).reshape(4,5)
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [12]:
my_matrix.T

array([[ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19],
       [ 5, 10, 15, 20]])

In [13]:
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [14]:
print(my_matrix[::-1,::-1])

[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


In [15]:
print(np.flip(my_matrix))

[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [16]:
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [17]:
print(my_matrix[:2,:2])

[[1 2]
 [6 7]]


## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [18]:
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [19]:
print(my_matrix[::2,::2])

[[ 1  3  5]
 [11 13 15]]


## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [20]:
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [21]:
print(my_matrix[:3,::-1])

[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]]


## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [22]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])

In [23]:
x == "Loro"

array([ True, False, False,  True, False])

In [24]:
x[x == "Loro"]

array(['Loro', 'Loro'], dtype='<U5')

In [25]:
print(np.where(x== "Loro")[0])

[0 3]


In [26]:
print(np.where(x == "Loro")[0])

[0 3]


In [27]:
x[np.where(x == "Loro")]

array(['Loro', 'Loro'], dtype='<U5')

In [28]:
# np.where(x == "Loro", x, np.nan)

## Ejercicio 9
Crea una secuencia de 20 elementos y transfórmala en un array compuesto por 2 matrices de 5x2

In [29]:
x = np.arange(20).reshape(2,5,2)
print(x)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]]


In [30]:
print(x.ndim)
print(x.shape)
print(x.size)

3
(2, 5, 2)
20


In [31]:
x = np.arange(20).reshape(10,2)
print(x)
m1,m2 = np.vsplit(x,[5])
print()
print(m1)
print()
print(m2)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]

[[10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


## Ejercicio 10

Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [32]:
import numpy as np

In [33]:
a_zeros = np.zeros(10)

In [34]:
a_zeros[3] = 1
a_zeros

array([0., 0., 0., 1., 0., 0., 0., 0., 0., 0.])

## Ejercicio 11

Crea un vector que vaya del 10 al 49

Inviértelo

In [35]:
vector =np.arange(10,50)


In [36]:
print(vector[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


## Ejercicio 12
Encuentra los índices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [1, 2 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/) Encapsúlalo en una función, con un argumento de entrada de un vector.

In [37]:
vector12 = np.array([1,2,0,0,4,0])

In [38]:
def valor_no_cero(vector):
    indices = np.nonzero(vector)[0]
    return indices


In [39]:
valor_no_cero(vector12)

array([0, 1, 4])

## Ejercicio 13
Crea una matriz de números aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [40]:
aleatory = np.random.randint(0,100, size = (10,10))
aleatory

array([[39, 52, 35,  0, 66, 62, 56, 10,  0, 52],
       [23,  5, 96, 91,  7, 76, 51, 33, 60, 23],
       [91, 91, 12, 32, 90, 92, 40,  9, 39, 82],
       [ 8, 78,  7, 75,  0, 40,  6, 93, 87, 38],
       [63, 95, 49, 81,  1, 23, 97, 39, 65, 36],
       [74, 42, 45, 25, 96, 76, 91, 99, 20, 17],
       [58, 69, 68, 53, 71, 55, 85, 23, 77, 42],
       [88, 57, 59, 23, 46, 77, 95, 45, 45, 87],
       [36, 48, 66, 30, 81, 21, 40, 25, 40,  8],
       [95, 94, 16, 66, 73, 58, 86, 33, 60, 98]], dtype=int32)

In [41]:
np.min(aleatory), np.max(aleatory)

(np.int32(0), np.int32(99))

## Ejercicio 14
Crea un vector aleatorio de tamaño 30 y calcula su media

In [42]:
vector_random = (np.random.rand(30))
vector_random

array([0.02691455, 0.74064728, 0.61935938, 0.71241812, 0.52764236,
       0.43875527, 0.26698598, 0.38123251, 0.98687584, 0.62038928,
       0.32852725, 0.95773297, 0.87901537, 0.75015321, 0.78239501,
       0.28741951, 0.0322543 , 0.47942723, 0.55820829, 0.47144086,
       0.3286755 , 0.18077575, 0.10210154, 0.02224009, 0.20925627,
       0.27803604, 0.14838896, 0.56548592, 0.08782983, 0.64321112])

In [43]:
vector3 = np.round(vector_random, 3)
vector3

array([0.027, 0.741, 0.619, 0.712, 0.528, 0.439, 0.267, 0.381, 0.987,
       0.62 , 0.329, 0.958, 0.879, 0.75 , 0.782, 0.287, 0.032, 0.479,
       0.558, 0.471, 0.329, 0.181, 0.102, 0.022, 0.209, 0.278, 0.148,
       0.565, 0.088, 0.643])

In [44]:
print(np.mean(vector3))

0.44703333333333334


## Ejercicio 15
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [45]:
aleat_matriz = np.random.randint(0,50, size = (5,5))
media = np.mean(aleat_matriz)
desviacion_estandar = np.std(aleat_matriz)
aleat_matriz_menos_media = aleat_matriz - media

print(np.std(aleat_matriz))
print(aleat_matriz)
print(aleat_matriz_menos_media)

matriz_normalizada = aleat_matriz_menos_media / desviacion_estandar
print(matriz_normalizada)

13.466759075590533
[[38 23  0 34 30]
 [16 13 27 19 32]
 [29 35  9 36 40]
 [18  3  0 40 38]
 [13 18  6 45 36]]
[[ 14.08  -0.92 -23.92  10.08   6.08]
 [ -7.92 -10.92   3.08  -4.92   8.08]
 [  5.08  11.08 -14.92  12.08  16.08]
 [ -5.92 -20.92 -23.92  16.08  14.08]
 [-10.92  -5.92 -17.92  21.08  12.08]]
[[ 1.04553738 -0.06831636 -1.77622544  0.74850972  0.45148205]
 [-0.58811478 -0.81088552  0.2287113  -0.36534403  0.59999588]
 [ 0.37722513  0.82276663 -1.10791319  0.89702355  1.19405121]
 [-0.43960094 -1.55345469 -1.77622544  1.19405121  1.04553738]
 [-0.81088552 -0.43960094 -1.33068394  1.56533579  0.89702355]]


## Ejercicio 16
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya por el valor -1, todos los elementos cuyo valor se encuentre entre el 3 y el 8.
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [46]:
array_16 = np.arange(0, 11)

In [47]:
array_16

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [48]:
nuevoarray_16 = array_16.copy()

nuevoarray_16[(nuevoarray_16 >= 3) & (nuevoarray_16 <= 8)] = -1
nuevoarray_16

array([ 0,  1,  2, -1, -1, -1, -1, -1, -1,  9, 10])

In [50]:
nuevoarray_17 = array_16.copy()

print(nuevoarray_17)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [51]:
nuevoarray_17[(nuevoarray_17 >= 3) & (nuevoarray_17 <= 8)] = False

In [52]:
nuevoarray_17

array([ 0,  1,  2,  0,  0,  0,  0,  0,  0,  9, 10])